#ifndef _VERSION_INFO_H 
#define _VERSION_INFO_H 
#define DATESTAMP "2016-10-31"  
#define MAJORVERSION 1 
#define MINORVERSION  4
#define SUBMINORVERSION  2
#define BUILDVERSION 0000
#if 0 
MAJORVERSION=1 
MINORVERSION=4
SUBMINORVERSION= 0
BUILDVERSION=0000
#endif 
#endif 
